# Generated by Django 3.0.8 on 2020-07-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20200718_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='last_name',
        ),
    ]
