# Generated by Django 3.0.8 on 2020-07-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_heroimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeroImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
