# Generated by Django 3.0.8 on 2020-07-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_auto_20200725_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
