# Generated by Django 3.0.8 on 2020-08-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_order_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collected',
            field=models.BooleanField(default=False),
        ),
    ]
