# Generated by Django 3.0.8 on 2020-08-06 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0017_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
    ]
