# Generated by Django 3.0.8 on 2020-08-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_stripepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StripePayment',
        ),
    ]
