# Generated by Django 3.0.8 on 2020-08-14 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0023_delete_stripepayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
